- hosts: all
  tasks:

  - file:
     state: directory
     path: "/appdvd"

  - mount:
     src: "/dev/cdrom"
     path: "/mount"
     state: mounted
     fstype: "iso9660"

  - yum_repository:
     baseurl: "/mount/AppStream"
     name: "RepO1"
     description: "This is the configuration for the Yum !"
     gpgcheck: no

  - yum_repository:
     baseurl: "/mount/BaseOS"
     name: "RepO2"
     description: "This is the configuration for the Yum !"
     gpgcheck: no
  
  - package:
     name: "httpd"
     state: present
  
  - copy:
     dest: "/var/www/html/index.html"
     content: "Welcome TO Coding Pathshala \n"   

  - service:
     name: "httpd"
     state: started
     enabled: yes
  
  - firewalld:
     port: 80/tcp
     state: enabled
     immediate: yes    
