- hosts: all
  tasks:

  - file:
     state: directory
     path: "/mount"

  - mount:
     src: "/dev/cdrom"
     path: "/mount"
     state: mounted
     fstype: "iso9660"

  - yum_repository:
     baseurl: "/mount/AppStream"
     name: "RepO1"
     description: "This is the configuration for the Yum !"
     gpgcheck: no

  - yum_repository:
     baseurl: "/mount/BaseOS"
     name: "RepO2"
     description: "This is the configuration for the Yum !"
     gpgcheck: no
  
  - package:
     name: "httpd"
     state: present
  
  - file:
     state: directory
     path: "/var/www/NewDir"

  - copy:
     dest: "/etc/httpd/conf.d/new.conf"
     src: "new.conf"
    register: info    
  
  - copy:
     dest: "/var/www/NewDir/index.html"
     content: "Welcome TO Coding Pathshala \n"   

  - name: "Normally Starting the Service of httpd"
    service:
     name: "httpd"
     state: started
     enabled: yes

    when: info.changed == false

  - firewalld:
     port: 8080/tcp
     state: enabled
     immediate: yes

  - name: "httpd_service_restart"
    service:
       name: "httpd"
       state: "restarted"
    when: info.changed == true
